version: "3.7"

services:
  db:
    image: mysql:latest
    container_name: blog-spot-bd
    volumes:
      - my-data-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - backend-network

volumes:
  my-data-volume:

networks:
  backend-network:
    driver: 'bridge'