version: "3.7"

services:
  backend:
    image: openjdk:19
    container_name: blogSpotContainer
    volumes:
      - ./build/libs/:/app
    working_dir: /app
    networks:
      - backend-network
    command: |
      java -jar blog-spot-0.0.1-SNAPSHOT.jar
    env_file:
      - .env
    ports:
      - "8000:8080"
  db:
    image: mysql:latest
    container_name: blog-spot-bd
    volumes:
      - my-data-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - backend-network

volumes:
  my-data-volume:

networks:
  backend-network:
    driver: 'bridge'