version: "3.7"

services:
  backend:
      image: mysql:latest
      container_name: blog-spot-bd
      volumes:
        - my-data-volume:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: 12345
        MYSQL_DATABASE: blogSpot
        MYSQL_USER: admin
        MYSQL_PASSWORD: 12345
      ports:
        - "3306:3306"
volumes:
  my-data-volume: